### ISSUE TITLE
Idea: Allow others to accept PR

### ISSUE THREAD

**Issue by shams-ahmed** [dbgrandi/Flurry#32]
Wouldn't it be better if there was more then one person with contributor write permission?

It would allow developers to always have the most recent version of Flurry SDK without having to depend on the repo owner of implementing or accepting PR...

**Comment by mergesort** [comment]
I would really like this too, it is kind of arbitrary when this repo gets updated. :+1:

**Comment by dbgrandi** [comment]
I agree. I'm working on migrating this back into Flurry. Step 1 was getting the repo transferred from @AntonPalich to me. Step 2 will be to transfer it into Flurry, and make sure we don't break older versions while doing that.

By then, they should be releasing new versions here and PR's will no longer be needed.
