### ISSUE TITLE
Will not build with use_frameworks

### ISSUE THREAD

**Issue by mergesort** [dbgrandi/Flurry#33]
The framework appears to be missing the umbrella header, needed for it to build with Frameworks in Swift.

**Comment by alistra** [comment]
+1

`The 'Pods' target has transitive dependencies that include static binaries: ([...]/Pods/FlurrySDK/Flurry/libFlurry_6.4.0.a`

**Comment by khaullen** [comment]
+1

**Comment by fabioknoedt** [comment]
+1

**Comment by marcioarantes-ww** [comment]
+1

**Comment by earltedly** [comment]
+1 also confirmed not working on 6.6. I don't get a framework appear for Flurry.

**Comment by earltedly** [comment]
Some extra information if this helps. I've dived into the build error a bit more and it seems like the include path for Flurry is not getting set. Thus if I add '"$(PODS_ROOT)/FlurrySDK/Flurry"' to the 'Header search paths' for my main target then everything works.

**Comment by justMaku** [comment]
We have encountered the same problem and managed to fix it, please look at the #41 to see the details.

**Comment by dbgrandi** [comment]
I merged in #44 from @justMaku and pushed out `6.7.0`. I'll close this, but feel free to re-open if needed.
