### ISSUE TITLE
Version 6.4.0 Podspec does not include FlurryWatch.h upon installation with `pod install`

### ISSUE THREAD

**Issue by vandadschibsted** [dbgrandi/Flurry#34]
As the title says, version `6.4.0` of the Podspec has problem brining the `FlurryWatch.h` file into the project upon `pod install`...

**Comment by dbgrandi** [comment]
@vandadschibsted is this still a problem in newer versions?

**Comment by dbgrandi** [comment]
Closing for now, re-open if it's still valid.
