### ISSUE TITLE
retransmitNotSentBlocks Crash

### ISSUE THREAD

**Issue by AmilaDiman** [dbgrandi/Flurry#36]
Please refer to the issue reported in the following link:
http://stackoverflow.com/questions/30242618/flurry-retransmitnotsentblocks-crash/30723000#30723000

Need an answer soon.

**Comment by kvting** [comment]
+1

**Comment by newangle121** [comment]
+1

**Comment by AntonPalich** [comment]
Can't do anything until Flurry fix it. I just support podspec

**Comment by jstart** [comment]
Do we know if there is a support URL where we can file this as a bug?

**Comment by jstart** [comment]
Stick to 6.2.0 version for now. They are working on a fix.

From Flurry:
flurrydev commented 32 seconds ago
We are aware of this crash. It happens occasionally when the device that was previously off line attempts to send the session data to the Flurry servers. The team is working to fix it, we are expecting the update to be released around 6/26.

**Comment by AmilaDiman** [comment]
+1

**Comment by kvting** [comment]
6.6 is out. Could you please update it and the pod?

**Comment by dbgrandi** [comment]
`6.6.0` and `6.7.0` are out. Should be fixed in both of those.
