### ISSUE TITLE
Upgrade version to 6.7.0 please.

### ISSUE THREAD

**Issue by mdebnam** [dbgrandi/Flurry#43]
It seems that there was a critical bug in the 6.6.0 release. 

Quote from flurry support:

This is a known bug with iOS v6.6. Only events with parameters are reported to the dashboard. We actually rolled back this SDK shortly after release.

It would be great if this repo (and the associated cocoapod distribution) could be updated to 6.7.0.

Thanks!

**Comment by TotemTraining** [comment]
Yes.  Ditto here.

**Comment by hakanw** [comment]
+1

**Comment by anilsdas** [comment]
+1

**Comment by eofs** [comment]
+1

**Comment by tutipeti** [comment]
+1 Pretty please?

**Comment by CraigSiemens** [comment]
+1

**Comment by Dids** [comment]
While this pod has been updated to 6.7.0 15 days ago, it seems to be broken, because it's referencing Flurry_6.6.0 for me, causing the following error:
```objc
ld: library not found for -lFlurry_6.6.0
```

**Comment by dbgrandi** [comment]
`6.7.0` should be live.
