### ISSUE TITLE
Cocoapods SDK Doesn't Compile

### ISSUE THREAD

**Issue by shnhrrsn** [dbgrandi/Flurry#46]
The pod is including "FlurryAdNative+Private.h" which exists, but is including private headers that don't, preventing it from compiling.

**Comment by dbgrandi** [comment]
@shnhrrsn Flurry has opened an [official repo](https://github.com/flurry/Flurry-iOS-SDK) to release via CocoaPods. I'd love to get people moving over there to help out.

The plan is to mark this pod deprecated in favor of the official pod once they get a release published.
